{{- if not .Values.config.oidcSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-tagging-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  ATTR_SERVICE_AUTH_CLIENT_SECRET: {{ .Values.config.oidcClientSecret | quote }}
  CONFIG_SERVICE_AUTH_CLIENT_SECRET: {{ .Values.config.oidcClientSecret | quote }}
{{- end }}