apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.lib.fullname" . }}-tagging-cm
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
  LOG_LEVEL: {{ .Values.config.logLevel | quote }}
  GRPC_PORT: {{ .Values.service.port | quote }}
{{- if .Values.config.configFile }}
  CONFIG_PATH: "/tagging-pdp/config.yaml"
{{- else }}
  CONFIG_ARTIFACT_ID: {{ .Values.config.configSvc.artifactId | quote }}
  CONFIG_SERVICE_ENDPOINT: {{ .Values.config.configSvc.url | quote }}
  CONFIG_SERVICE_POLLING_MAX: {{ .Values.config.configSvc.pollingMax | quote}}
  CONFIG_SERVICE_POLLING_MIN: {{ .Values.config.configSvc.pollingMin | quote}}
  CONFIG_SERVICE_AUTH_CLIENT_ID: {{ .Values.config.oidcClientId | quote}}
{{- if .Values.config.attrSvc.url }}
  ATTR_SERVICE_POLLING_MAX: {{ .Values.config.attrSvc.pollingMax | quote}}
  ATTR_SERVICE_POLLING_MIN: {{ .Values.config.attrSvc.pollingMin | quote}}
  ATTR_SERVICE_AUTH_CLIENT_ID: {{ .Values.config.oidcClientId | quote}}
  ATTR_SERVICE_ENDPOINT: {{ .Values.config.attrSvc.url | quote}}
{{- end}}
{{- end }}

