apiVersion: v1
kind: ConfigMap
metadata:
  name: audit-api-cm
  labels:
    app: audit-api
data:
  POSTGRES_HOST: {{ (coalesce .Values.config.db.host) | quote }}
  POSTGRES_READER: {{ (coalesce .Values.config.db.reader) | quote }}
  POSTGRES_USER: {{ .Values.config.db.user | quote }}
  POSTGRES_PORT: {{ (coalesce .Values.config.db.port) | quote }}
  POSTGRES_DB: {{ .Values.config.db.dbName | quote }}
  POSTGRES_SSLMODE: {{ .Values.config.db.sslMode | quote }}
  SELF_HOSTED_PLATFORM: "true"
  PLATFORM_DISABLE_AUTH: {{ .Values.image.disableInternalAuth | default "true" | quote }}
  CONFIG_ORG_ID: {{ .Values.config.platform.defaultOrgId | default "00000000-0000-0000-0000-000000000000" | quote }}
