apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "common.lib.fullname" . }}
spec:
  gateways: [{{ include "platform.ingress.gateway" . }}]
  hosts:
    - '*'
  http:
    - match:
      - uri:
          prefix: /audit/
      - uri:
          prefix: /audit
      name: audit
      rewrite:
        uri: /
      route:
      - destination:
          host: audit-api
          port:
            number: {{ .Values.service.port }}
