{{- if .Values.istioAuth.enabled }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: audit-jwt-authentication
spec:
  selector:
    matchLabels:
      {{- include "common.lib.selectorLabels" . | nindent 6 }}

  jwtRules:
    - issuer: {{ include "platform.auth.issuer" $ | quote }}
      jwksUri: {{ include "platform.auth.jwksUri" $ | quote }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: audit-external
spec:
  selector:
    matchLabels:
      {{- include "common.lib.selectorLabels" . | nindent 6 }}
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
---
{{- end }}