{{/*
  Secret for keycloak admin user and db connection values
  */}}
{{- $tspassword := ( randAlphaNum 32 | quote ) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-extraenv
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.adminUsername }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.adminPassword}}
  KC_DB_USERNAME: "keycloak_manager"
  KC_DB_PASSWORD: {{ .Values.secrets.keycloak.dbPassword }}
  KC_DB_URL_HOST: {{ .Values.global.opentdf.common.postgres.host }}
  KC_DB_URL_DATABASE: {{ .Values.keycloak.externalDatabase.database }}
{{- if .Values.keycloak.trustedCertSecret }}
  JKS_TRUSTSTORE_PASSWORD: {{ $tspassword }}
  KC_SPI_TRUSTSTORE_FILE_PASSWORD: {{ $tspassword }}
  KC_HTTPS_KEY_STORE_PASSWORD: {{ $tspassword }}
{{- end }}