apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.name }}-gateway
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
spec:
  selector:
    istio: {{ .Values.ingress.gatewaySelector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - {{ include "scp.ingressHostname" . }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https-443
        {{- if .Values.ingress.tls.enabled }}
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "scp.ingress.tlsCredName" . }}
        {{- else }}
        protocol: HTTP2
        {{- end }}
      hosts:
        - {{ include "scp.ingressHostname" . }}
---
{{- if .Values.ingress.tls.enabled }}
{{- if not .Values.ingress.tls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "scp.ingress.tlsCredName" . }}
  namespace: {{ include "scp.ingress.tlsNs" . }}
type: kubernetes.io/tls
data:
  {{ ( include "scp.ingress.gen-certs" . ) }}
{{- end }}
{{- end }}