apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ .Values.ingress.name }}-gateway
  labels:
    {{- include "scp.labels" . | nindent 4 }}
spec:
  selector:
    istio: {{ .Values.ingress.gatewaySelector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - {{ include "scp.ingressHostname" . }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https-443
        protocol: HTTP
      hosts:
        - {{ include "scp.ingressHostname" . }}