apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: tagging-pdp
spec:
  gateways:
    - {{ include "scp.ingress.gateway" . }}
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: /virtru.tagging.pdp.TaggingPDPService
        - uri:
            prefix: /grpc.reflection.v1alpha.ServerReflection
      name: tagging-pdp
      route:
        - destination:
            host: tagging-pdp
            port:
              number: 15001
      timeout: 10s
