{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-configsvc
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: {{ .Values.secrets.configuration.postgres.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-attributes-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.attributes.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlements-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.entitlements.dbPassword | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.oidcClientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlement-store-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.entitlementStore.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlement-pdp-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret | default "opaPolicyPullSecret" }}
---
{{- if .Values.embedded.postgresql }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "postgresql.primary.fullname" .Subcharts.postgresql }}-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgres.dbPassword }}
---
{{- end }}
{{/*
  Secret for keycloak admin user and db connection values
*/}}
{{- if .Values.embedded.keycloak }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-keycloak-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.admin.user }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.admin.password}}
  KC_DB_USERNAME: "keycloak_manager"
  KC_DB_PASSWORD: {{ .Values.secrets.keycloak.postgres.password }}
  KC_DB_URL_HOST: {{ .Values.global.opentdf.common.postgres.host }}
  KC_DB_URL_DATABASE: {{ .Values.keycloak.externalDatabase.database }}
---
{{- end }}
{{- end }}

