apiVersion: v1
kind: Service
metadata:
  name: {{ include "configuration.fullname" . }}
  labels:
    {{- include "configuration.labels" . | nindent 4 }}
spec:
  type: {{ .Values.server.service.type }}
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    {{- include "configuration.selectorLabels" . | nindent 4 }}
