{{- if .Values.externalAppSecrets }}
{{ range .Values.externalAppSecrets }}
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .name }}
  labels:
    {{- include "cse.labels" $ | nindent 4 }}
spec:
  dataFrom:
  - extract:
      key: {{ required "secretsPath is required" .secretsPath }}
  target:
    name: {{ .name }}
  secretStoreRef:
    kind: {{ .secretStoreRef.kind }}
    name: {{ .secretStoreRef.name }}
  refreshInterval: {{ .refreshInterval | default "1h" }}
{{- end }}
{{- end }}
