apiVersion: v1
kind: Service
metadata:
  name: {{ include "cse.fullname" . }}
  labels:
    {{- include "cse.labels" . | nindent 4 }}
  {{- if .Values.service.annotations}}
  annotations:
    {{- toYaml .Values.service.annotations  | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - {{- if .Values.service.portName }}
      name: {{ .Values.service.portName }}
      {{- end }}
      port: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
      targetPort: {{ .Values.deployment.port }}
  selector:
    {{- include "cse.selectorLabels" . | nindent 4 }}