{{- if .Values.config.configFile }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.lib.fullname" . }}-taggingconfig-cm
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
  config.yaml: {{ .Values.config.configFile | quote }}
{{- end }}
