{{- if .Values.istioAuth.enabled }}
{{- $root := . -}}
{{ range $entry :=  .Values.istioAuth.policies }}
apiVersion: security.istio.io/v1beta1
kind: RequestAuthentication
metadata:
  name: {{ include "common.lib.name" $ }}-{{ $entry.name }}-jwt-authentication
spec:
  selector:
    matchLabels:
      {{- tpl $entry.selectorLabels $ | nindent 6 }}
  jwtRules:
    - issuer: {{ include "shp.auth.issuer" $ | quote }}
    {{- if $.Values.embedded.keycloak }}
      jwksUri: {{ include "shp.authinternal.jwksUri" $ | quote }}
    {{- else }}
      jwksUri: {{ include "shp.auth.jwksUri" $ | quote }}
    {{- end }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "common.lib.name" $ }}-{{ $entry.name }}-external
spec:
  selector:
    matchLabels:
      {{- tpl $entry.selectorLabels $ | nindent 6 }}
  action: ALLOW
  rules:
    - from:
      - source:
          requestPrincipals: ["*"]
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: {{ include "common.lib.name" $ }}-{{ $entry.name }}-internal
spec:
  selector:
    matchLabels:
      {{- tpl $entry.selectorLabels $ | nindent 6 }}
  action: ALLOW
  rules:
    - from:
      - source:
          namespaces: [ {{ $.Release.Namespace }} ]
---
{{- end }}
{{- end }}
