apiVersion: v2
name: platform
description: Self Hosted Data Protection Platform
type: application
version: 0.3.8
appVersion: 0.1.4

otdfVersion: &otdfVersion "1.6.0"
otdfRepo: &otdfRepo "oci://ghcr.io/opentdf/charts"

dependencies:
  - name: abacus
    repository: *otdfRepo
    version: '1.6.0'
    condition: abacus.enabled

  - name: attributes
    repository: *otdfRepo
    version: *otdfVersion
    condition: attributes.enabled

  - name: entitlement-pdp
    repository: *otdfRepo
    version: *otdfVersion
    condition: entitlement-pdp.enabled

  - name: entitlement-store
    repository: *otdfRepo
    version: *otdfVersion
    condition: entitlement-store.enabled

  - name: entitlements
    repository: *otdfRepo
    version: *otdfVersion
    condition: entitlements.enabled

  - name: entity-resolution
    repository: *otdfRepo
    version: *otdfVersion
    condition: entity-resolution.enabled

  - name: kas
    repository: *otdfRepo
    version: *otdfVersion
    condition: kas.enabled

  - name: common-lib
    repository: file://../common-lib
    version: 0.1.0

  - name: access-pep
    repository: oci://ghcr.io/virtru-corp/charts
    version: '0.1.0-sha-574135b'
    condition: access-pep.enabled

  - name: tagging-pdp
    repository: file://./charts/tagging-pdp
    version: '0.1.0'
    condition: tagging-pdp.enabled

  - name: configuration
    repository: file://./charts/configuration
    version: '0.4.0'
    condition: configuration.enabled

  # Private OCI Registry for OPA Policy Bundles
  - name: docker-registry
    repository: https://helm.twun.io
    version: 2.2.2
    condition: docker-registry.enabled

  - name: keycloak-bootstrap
    repository: *otdfRepo
    version: *otdfVersion
    condition: bootstrap.attrDefOrEntitlements
    alias: entitlement-attrdef-bootstrap
    tags: ["bootstrap"]

  - name: opcr-policy
    repository: file://./charts/opcr-policy
    alias: entitlement-policy-bootstrap
    version: 0.1.0
    condition: bootstrap.entitlementPolicy
    tags: ["bootstrap"]
