# Default values for the platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# Some yaml anchor definitions for convenience
## @section Common parameters - used as yaml anchors
commonParams:
  ## @param commonParams.attrEndpoint Interal attribute service endpoint
  attrEndpoint: &attrEndpoint "http://attributes:4020"
  ## @param commonParams.disableTracing Disable OTEL Tracing
  disableTracing: &disableTracing "true"
  ## @param commonParams.entitlementPolicyBundleRepo entitlement OPA Bundle Repo
  entitlementPolicyBundleRepo: &entitlementPolicyBundleRepo "docker-registry:5000/entitlements-policybundle"
  ## @param commonParams.entitlementPolicyBundleTag entitlement OPA Bundle tag
  entitlementPolicyBundleTag: &entitlementPolicyBundleTag 0.0.2
  ## @param commonParams.entilementPolicyOCIRegistryUrl OPA policy endpoint
  entilementPolicyOCIRegistryUrl: &entilementPolicyOCIRegistryUrl "https://docker-registry:5000"
  ## @param commonParams.platformImagePullSecretName common pull secret name
  platformImagePullSecretName:
  imagePullSecrets:
    ## @param commonParams.imagePullSecrets[0].name name of pull secret
    - name:
  ## @param commonParams.jobWaitForIstio Job needs to wait for istio and exit appropriately
  jobWaitForIstio: &istioTerminationHack true

## @section General / Misc Parameters
## @param nameOverride Chart name override
nameOverride: ""
## @param fullnameOverride Chart full name override
fullnameOverride: ""
embedded:
  ## @param embedded.keycloak  Is keycloak in the cluster
  keycloak: true
keycloak:
  ## @param keycloak.realm  If using keycloak - the realm name
  realm: tdf

## @section Attribute Definition and Entitlement bootstrap parameters
bootstrap:
  ## @param bootstrap.attrDefOrEntitlements Should entitlements and/or attributes be bootstrapped.
  attrDefOrEntitlements: true
  ## @param bootstrap.oidcClientOrg The OIDC Org for bootstrap client authentication
  oidcClientOrg: tdf
  ## @param bootstrap.oidcClientId The OIDC ClientID for boostrap client authentication
  oidcClientId: dcr-test
  configsvc:
    ## @param bootstrap.configsvc.enabled Enable configuration service artifact bootstrapping
    enabled: true
    job:
      ## @param bootstrap.configsvc.job.name Name of the job
      name: configsvc-bootstrap
      image:
        ## @param bootstrap.configsvc.job.image.repo Image repository
        repo: ghcr.io/virtru-corp/postman-cli/opcr-policy
        ## @param bootstrap.configsvc.job.image.tag Image tag
        tag: sha-91e572c
        ## @param bootstrap.configsvc.job.image.pullPolicy Image pull policy
        pullPolicy: IfNotPresent
      ## @param bootstrap.configsvc.job.backoffLimit Job backoff limit
      backoffLimit: 5
      ## @param bootstrap.configsvc.job.configVolumeSecretRefName Secret name used to mount configuration artifacts used by the job
      configVolumeSecretRefName: platform-bootstrap-configsvc
      ## @param bootstrap.configsvc.job.envSecretRef secret for environment variables
      envSecretRef:
  ## @param  bootstrap.configFile The configuration file content (set using --set-file bootstrap.configFile=yourconfig.yaml
  configFile:
  ## @param bootstrap.entitlementPolicy Should entitlement policy be bootstrapped
  entitlementPolicy: true

## @section Ingress Configuration
ingress:
  ## @param ingress.existingGateway Use an existing istio gateway
  existingGateway:
  ## @param ingress.gatewaySelector Name of istio gateway selector
  gatewaySelector: ingress
  ## @param ingress.name Name base for istio resources
  name: platform
  tls:
    ## @param ingress.tls.enabled Require Gateway to use tls
    enabled: false
    ## @param ingress.tls.existingSecret Use existing TLS Secret
    existingSecret:

## @section Istio AuthN/Z Parameters
istioAuth:
  ## @param istioAuth.enabled Turn on/off istio authentication configuration for services defined by the `istioAuth.policies` configuration
  enabled: true
  ## @param istioAuth.internalJWTURL Whether to compute and use internal keycloak jwks uri - default false
  internalJWTURL: true
  ## @extra istioAuth.policies List of in format : [ {name: <k8s compliant resource name part>, selectorLabels: yaml template for selector labels } ]
  ## @skip istioAuth.policies
  policies:
    - name: taggingpdp
      labelName:
      selectorLabels: |-
        app.kubernetes.io/name: {{ index $.Values "tagging-pdp" "fullnameOverride" }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    - name: taggingpdp-grpc-gateway
      selectorLabels: |
        app.kubernetes.io/name: {{ index $.Values "tagging-pdp" "fullnameOverride" }}-grpc-gwy
        app.kubernetes.io/instance: {{ $.Release.Name }}
    - name: configsvc
      selectorLabels: |
        app.kubernetes.io/name: {{ index $.Values "configuration" "fullnameOverride" }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    - name: entitlement-pdp
      selectorLabels: |
        app.kubernetes.io/name: {{ index $.Values "entitlement-pdp" "fullnameOverride" }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
global:
  ## @param global.istioEnabled Istio enabled true/false
  istioEnabled: true
  ## @skip global.opentdf
  opentdf:
    common:
      oidcExternalBaseUrl: https://shp.example.com
      oidcInternalBaseUrl: http://keycloak-http
      oidcUrlPath: auth
      ingress:
        scheme: "https"
        hostname: "example.com"
      postgres:
        # -- postgres server's k8s name or global DNS for external server
        host: postgresql
        # -- postgres server port
        port: 5432
        # -- The database name within the given server
        database: tdf_database
  ## @param global.imagePullSecrets global pull secrets
  imagePullSecrets:

## @section ABACUS Chart Overrides
abacus:
  ## @param abacus.enabled abacus enabled flag
  enabled: true
  ## @param abacus.basePath path to abcus
  basePath: "/abacus"
  ## @param abacus.fullnameOverride Override name of abacus
  fullnameOverride: abacus
  ## @skip abacus.ingress
  ingress:
    enabled: false

## @section Access-PEP Chart Overrides
access-pep:
  ## @param access-pep.enabled Enable access-pep flag
  enabled: true
  ## @param access-pep.name Name override
  name: access-pep
  ## @param access-pep.fullnameOverride Access-Pep Name Override
  fullnameOverride: access-pep
  ## @param access-pep.existingImagePullSecret Existing pull secret for the image
  existingImagePullSecret:
  ## @skip access-pep.useImagePullSecret
  useImagePullSecret: false
  image:
    ## @param access-pep.image.repo Image Rep
    repo: ghcr.io/virtru-corp/access-pep/access-pep
    ## @param access-pep.image.tag Image tag
    tag: 0.1.0-sha-574135b
  config:
    ## @param access-pep.config.disableTracing disable tracing flag
    disableTracing: *disableTracing
    ## @param access-pep.config.attrAuthorityHost Attribute Service Endpoint
    attrAuthorityHost: *attrEndpoint
    ## @param access-pep.config.entitlementPdpHost entitlement pdp endpoint
    entitlementPdpHost: "http://entitlement-pdp:3355"
    ## @param access-pep.config.keycloakAttrAuthorityClientID OIDC client id
    keycloakAttrAuthorityClientID: "tdf-client"
    ## @param access-pep.config.keycloakAttrAuthorityClientSecret Sets client secret to empty - to be overridden by secret
    keycloakAttrAuthorityClientSecret:

## @section Attribute Chart Overrides
attributes:
  ## @param attributes.enabled Attributes Service enabled flag
  enabled: true
  ## @param attributes.fullnameOverride Attribute Service Name Override
  fullnameOverride: attributes
  ## @param attributes.secretRef Secrets for environment variable injection
  secretRef: |-
    name: platform-attributes-secret

## @section Configuration Chart Overrides
configuration:
  ## @param configuration.enabled Configuration Service enabled flag
  enabled: true
  ## @param configuration.fullnameOverride Configuration svc name override
  fullnameOverride: configuration
  server:
    image:
      ## @param configuration.server.image.tag Configuration Service Image Tag
      tag: 0.9.1
    ## @param configuration.server.secretRef Configuration Service Secrets Ref
    secretRef: |-
      name: platform-configsvc
    postgres:
      ## @param configuration.server.postgres.host hostname of postgres
      host: postgresql
      ## @param configuration.server.postgres.password password for postgres - should not be set
      password:
    ## @param configuration.server.imagePullSecrets Pull secrets for configuration service
    imagePullSecrets:

## @section Entitlement Policy Bootstrap Job parameters
entitlement-policy-bootstrap:
  ## @param entitlement-policy-bootstrap.bundleRepo Bundle repository
  bundleRepo: *entitlementPolicyBundleRepo
  ## @param entitlement-policy-bootstrap.bundleTag Bundle Tag
  bundleTag: *entitlementPolicyBundleTag
  ## @param entitlement-policy-bootstrap.OCIRegistryUrl URL of OCI registry to publish to
  OCIRegistryUrl: *entilementPolicyOCIRegistryUrl
  ## @param entitlement-policy-bootstrap.policyConfigMap Config map name used to inject env varibles into the job
  policyConfigMap: platform-bootstrap-entitlement-cm
  ## @param entitlement-policy-bootstrap.policyDataSecretRef Secret name used to mount policy artifacts into the job. To support source files outside this chart a secret created separate from this chart is required. Example to mount all files in directory: kubectl create secret generic platform-bootstrap-entitlement-policy --from-file=pathTo/entitlement-policy
  policyDataSecretRef: platform-bootstrap-entitlement-policy
  ## @param entitlement-policy-bootstrap.imagePullSecrets Pull secrets for entitlement policy bootstrap
  imagePullSecrets:
  ## @param entitlement-policy-bootstrap.istioTerminationHack Set istio on/off
  istioTerminationHack: *istioTerminationHack
  image:
    ## @param entitlement-policy-bootstrap.image.tag ocpr container tag
    tag: sha-91e572c

## @section Entitlement PDP Chart Overrides
entitlement-pdp:
  ## @param entitlement-pdp.enabled entitlement-pdp service enabled flag
  enabled: true
  ## @param entitlement-pdp.fullnameOverride  Entitlement PDP name override
  fullnameOverride: entitlement-pdp
  opaConfig:
    policy:
      ## @param entitlement-pdp.opaConfig.policy.useStaticPolicy Use static policy flag - false to pull from oci registry
      useStaticPolicy: false
      ## @param entitlement-pdp.opaConfig.policy.allowInsecureTLS Allow insecure comms to oci registry
      allowInsecureTLS: true
      ## @param entitlement-pdp.opaConfig.policy.OCIRegistryUrl OCI registry url
      OCIRegistryUrl: *entilementPolicyOCIRegistryUrl
      ## @param entitlement-pdp.opaConfig.policy.bundleRepo OCI Bundle Repo
      bundleRepo: *entitlementPolicyBundleRepo
      ## @param entitlement-pdp.opaConfig.policy.bundleTag OCI bundle tag
      bundleTag: *entitlementPolicyBundleTag
  config:
    ## @param entitlement-pdp.config.disableTracing Disable tracing flag
    disableTracing: *disableTracing
  ## @param entitlement-pdp.secretRef Secrets for env variables.
  secretRef: |-
    name: platform-entitlement-pdp-secret

## @section Entitlement Store Chart Overrides
entitlement-store:
  ## @param entitlement-store.enabled entitlement-store service enabled flag
  enabled: true
  ## @param entitlement-store.fullnameOverride Entitlement Store name override
  fullnameOverride: entitlement-store
  ## @param entitlement-store.secretRef Secrets for environment variables
  secretRef: |-
    name: platform-entitlement-store-secret

## @section Entitlement Chart Overrides
entitlements:
  ## @param entitlements.enabled entitlements service enabled flag
  enabled: true
  ## @param entitlements.fullnameOverride Entitlements Name Override
  fullnameOverride: entitlements
  ## @param  entitlements.secretRef Entitlements Secrets for environment variables
  secretRef: |-
    name: platform-entitlements-secret    

## @section Entity Resolution Chart Overrides
entity-resolution:
  ## @param entity-resolution.enabled entity-resolution service enabled flag
  enabled: true
  ## @param entity-resolution.fullnameOverride Entity Resolution Name override
  fullnameOverride: entity-resolution
  config:
    ## @param entity-resolution.config.disableTracing Disable Tracing Flag
    disableTracing: *disableTracing
    keycloak:
      ## @param entity-resolution.config.keycloak.legacy Legacy Keycloak Tracing Flag
      legacy: true

## @section KAS Chart Overrides
kas:
  ## @param kas.enabled kas service enabled flag
  enabled: true
  ## @param kas.fullnameOverride  KAS Name Override
  fullnameOverride: kas
  endpoints:
    ## @param kas.endpoints.attrHost Attributes hostname accessible to KAS
    attrHost: *attrEndpoint
  pdp:
    ## @param kas.pdp.verbose Verbose Logging Flag
    verbose: "true"
    ## @param kas.pdp.disableTracing  Disable tracing flag
    disableTracing: *disableTracing

## @section Attribute Definition / Entitlements Bootstrap Chart Overrides
entitlement-attrdef-bootstrap:
  entitlements:
    ## @param entitlement-attrdef-bootstrap.entitlements.hostname Entitlement svc hostname
    hostname: http://entitlements:4030
    ## @param entitlement-attrdef-bootstrap.entitlements.realms Entitlement override realms
    realms: null
  ## @param entitlement-attrdef-bootstrap.existingConfigSecret Secret name used to Mount bootstrapping data
  existingConfigSecret: platform-keycloakbootstrap-config
  ## @param entitlement-attrdef-bootstrap.istioTerminationHack Set istio on/off
  istioTerminationHack: *istioTerminationHack
  ## @param entitlement-attrdef-bootstrap.secretRef Secret for bootstrap job env variables.
  secretRef: |-
    name: platform-keycloakbootstrap-secret
  attributes:
    ## @param entitlement-attrdef-bootstrap.attributes.hostname Attribute service endpoint accessible to boostrap job
    hostname: *attrEndpoint
    ## @param entitlement-attrdef-bootstrap.attributes.realm Realm for OIDC client auth to attribute service
    realm: tdf
    ## @param entitlement-attrdef-bootstrap.attributes.clientId OIDC client ID used to auth to attribute service
    clientId: dcr-test

## @section Docker Registry Configuration
docker-registry:
  ## @param docker-registry.enabled Enable docker registry
  enabled: true
  ## @param docker-registry.fullnameOverride Override name of service
  fullnameOverride: docker-registry
  persistence:
    ## @param docker-registry.persistence.enabled Persistence Enabled Flag
    enabled: true
    ## @param docker-registry.persistence.size Size of volume
    size: 1Gi
  ## @param docker-registry.tlsSecretName Secret name containing TLS Certs used by the registry
  tlsSecretName: platform-docker-registry-certs
  ## @skip docker-registry.securityContext
  securityContext:
    enabled: false
    fsGroup: null
    runAsUser: null

## @section Secret Generation Parameters
secrets:
  ## @param secrets.enabled Generate secrets from the values provided below.  If false, another bootstrapping
  # mechanism for secrets is required.
  enabled: true
  postgresql:
    ## @param secrets.postgresql.dbPassword password for postgres user
    dbPassword:
  attributes:
    ## @param secrets.attributes.clientSecret oidc client secret used by attributes svc to auth to idp and enforce svc authorization
    clientSecret:
    ## @param secrets.attributes.dbPassword postgres password for attributes svc user
    dbPassword:
  configuration:
    ## @param secrets.configuration.dbPassword postgres password for config svc user
    dbPassword:
  entitlementStore:
    ## @param secrets.entitlementStore.dbPassword postgres password for entitlement-store svc user
    dbPassword:
  entitlements:
    ## @param secrets.entitlements.clientSecret oidc client secret used by entitlements svc to auth to idp and enforce svc authorization
    clientSecret:
    ## @param secrets.entitlements.dbPassword postgres password for entitlements svc user
    dbPassword:
  keycloak:
    ## @param secrets.keycloak.adminUsername Optional for bootstrapping - keycloak username for user with admin role
    adminUsername:
    ## @param secrets.keycloak.adminPassword Optional for bootstrapping - keycloak password for user with admin role
    adminPassword:
  keycloakBootstrap:
    ## @param secrets.keycloakBootstrap.attributesUsername username for attribute service auth
    attributesUsername:
    ## @param secrets.keycloakBootstrap.attributesPassword password for attribute service auth
    attributesPassword:
    ## @param secrets.keycloakBootstrap.users list of users to be added [{"username":"","password":""}]
    users:
    ## @param secrets.keycloakBootstrap.clients list of custom oidc clients added [{"clientId":<>,"clientSecret":"","audienceMappers":["aud]}]
    clients:
    ## @param secrets.keycloakBootstrap.clientSecret client secret assigned to standard bootstrapper clients
    clientSecret:
    ## @param secrets.keycloakBootstrap.customConfig Override for custom config to none
    customConfig: null
  ## @param secrets.opaPolicyPullSecret oci registry pull secret for OPA policy
  opaPolicyPullSecret:
  taggingPDP:
    ## @param secrets.taggingPDP.clientSecret OIDC Client Secret for Tagging PDP
    clientSecret:
  ## @extra secrets.imageCredentials Map of key (pull name) to auth information.  Each key creates a pull cred
  imageCredentials:
    ## @extra secrets.imageCredentials.pull-secret Container registry auth for "install name"-pull-secret
    pull-secret:
      ## @param secrets.imageCredentials.pull-secret.registry Registry repo
      registry: ghcr.io
      ## @param secrets.imageCredentials.pull-secret.username Registry Auth username
      username: username
      ## @param secrets.imageCredentials.pull-secret.password Registry Auth password
      password: password
      ## @param secrets.imageCredentials.pull-secret.email Registry Auth email
      email: nope@nah.com

## @section Tagging PDP Chart Overrides
tagging-pdp:
  ## @param tagging-pdp.enabled enabled flag
  enabled: true
  ## @param tagging-pdp.fullnameOverride override name
  fullnameOverride: tagging-pdp
  image:
    ## @param tagging-pdp.image.tag Tagging PDP Image Tag
    tag: 0.2.7
    ## @param tagging-pdp.image.pullSecrets TaggingPDP image pull secrets
    pullSecrets:
  gateway:
    ## @param tagging-pdp.gateway.enabled Tagging PDP Rest Gateway enabled flag
    enabled: true
    ## @param tagging-pdp.gateway.pathPrefix tagging-pdp svc prefix
    pathPrefix: tagging-pdp
    ## @skip tagging-pdp.gateway.image
    image:
      tag: 0.2.7-82b7d18
  config:
    attrSvc:
      ## @param tagging-pdp.config.attrSvc.url Set the attribute service url
      url: *attrEndpoint
    ## @param tagging-pdp.config.oidcSecretName Use existing secret for OIDC Creds
    oidcSecretName: platform-tagging-pdp-secret
    ## @param tagging-pdp.config.oidcClientId OIDC Client ID for tagging pdp
    oidcClientId: shp-tagging-pdp

## @param tdfAdminUsername The admin user created for tdf.
tdfAdminUsername: tdf-admin
