{{- if not .Values.externalAppSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.virtruKeys.name }}
type: Opaque
{{- with .Values.appSecrets.virtruKeys.data }}
stringData:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
