{{- if and .Values.dsp.enabled (not .Values.externalAppSecrets) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.dspAuth.name }}
type: Opaque
stringData:
  CLIENT_ID: {{ .Values.appSecrets.dspAuth.data.clientId | quote }}
  CLIENT_SECRET: {{ .Values.appSecrets.dspAuth.data.clientSecret | quote }}
{{- end }}
