{{- if not .Values.externalAppSecrets }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.appSecrets.virtruAuth.name }}
type: Opaque
data:
  AUTH_TOKEN_STORAGE_IN_MEMORY_TOKEN_JSON: {{ .Values.appSecrets.virtruAuth.data.authTokenJson | b64enc | quote }}
{{- end }}
