{{- if and .Values.dkimSelector .Values.dkimPrivateKey }}
apiVersion: v1
kind: Secret
metadata:
  name: "{{ include "gateway.fullname" . }}-dkim"
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  {{ .Values.dkimSelector }}._domainkey.{{ .Values.primaryMailingDomain }}.pem: {{ .Values.dkimPrivateKey | b64enc | quote }}
{{- end }}
