apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  {{- if .Values.xHeaderAuthSecret }}
  gateway-xheader-auth-secret: "{{ .Values.appSecrets.headers.xHeaderAuthSecret | b64enc | quote }}"
  {{- end }}
  {{- if .Values.smtpdUpstreamCredentials }}
  gateway-sasl-auth-upstream: {{ .Values.smtpdUpstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if .Values.smtpDownstreamCredentials }}
  gateway-sasl-auth-downstream: {{ .Values.smtpDownstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if .Values.abacOidcClientSecret }}
  gateway-abac-oidc-client-secret: {{ .Values.abacOidcClientSecret | b64enc | quote }}
  {{- end }}
