{{- if not .Values.existingSecret.name }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  {{- if .Values.xHeaderAuthSecret }}
  gateway-xheader-auth-secret: {{ .Values.xHeaderAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if .Values.saslUpstreamCredentials }}
  gateway-sasl-auth-upstream: {{ .Values.saslUpstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if .Values.saslDownstreamCredentials }}
  gateway-sasl-auth-downstream: {{ .Values.saslDownstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if .Values.abacOidcClientSecret }}
  gateway-abac-oidc-client-secret: {{ .Values.abacOidcClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
