{{- $needsSecret := false }}
{{- if and .Values.xHeaderAuthSecret (not (and .Values.existingSecret.name .Values.existingSecret.xHeaderAuthSecretName)) }}
  {{- $needsSecret = true }}
{{- end }}
{{- if and .Values.saslUpstreamCredentials (not (and .Values.existingSecret.name .Values.existingSecret.saslUpstreamCredentialsName)) }}
  {{- $needsSecret = true }}
{{- end }}
{{- if and .Values.saslDownstreamCredentials (not (and .Values.existingSecret.name .Values.existingSecret.saslDownstreamCredentialsName)) }}
  {{- $needsSecret = true }}
{{- end }}
{{- if and .Values.abacOidcClientSecret (not (and .Values.existingSecret.name .Values.existingSecret.abacOidcClientSecretName)) }}
  {{- $needsSecret = true }}
{{- end }}
{{- if $needsSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  {{- if and .Values.xHeaderAuthSecret (not (and .Values.existingSecret.name .Values.existingSecret.xHeaderAuthSecretName)) }}
  gateway-xheader-auth-secret: {{ .Values.xHeaderAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if and .Values.saslUpstreamCredentials (not (and .Values.existingSecret.name .Values.existingSecret.saslUpstreamCredentialsName)) }}
  gateway-sasl-auth-upstream: {{ .Values.saslUpstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if and .Values.saslDownstreamCredentials (not (and .Values.existingSecret.name .Values.existingSecret.saslDownstreamCredentialsName)) }}
  gateway-sasl-auth-downstream: {{ .Values.saslDownstreamCredentials | b64enc | quote }}
  {{- end }}
  {{- if and .Values.abacOidcClientSecret (not (and .Values.existingSecret.name .Values.existingSecret.abacOidcClientSecretName)) }}
  gateway-abac-oidc-client-secret: {{ .Values.abacOidcClientSecret | b64enc | quote }}
  {{- end }}
{{- end }}
