apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.lib.fullname" . }}-configmap
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
  POSTGRES_HOST: {{ (coalesce .Values.config.db.host .Values.global.opentdf.common.postgres.host) | quote }}
  POSTGRES_USER: {{ .Values.config.db.user | quote }}
  POSTGRES_PORT: {{ (coalesce .Values.config.db.port .Values.global.opentdf.common.postgres.port) | quote }}
  POSTGRES_DB: {{ .Values.config.db.dbName | quote }}
  POSTGRES_SSLMODE: {{ .Values.config.db.sslMode | quote }}
  AUTH_URL: {{ .Values.config.auth.url | quote }}
  AUTH_ORGANIZATION: {{ (coalesce .Values.config.auth.org .Values.global.auth.organization ) | quote }}
  AUTH_CLIENT_ID: {{ .Values.config.auth.clientId | quote }}
  CONFIG_URL: {{ .Values.config.configSvc.url | quote }}

