apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "common.lib.fullname" . }}
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "common.lib.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "common.lib.selectorLabels" . | nindent 8 }}
    spec:
      {{ include "sharepoint.imagePullSecrets" . | nindent 6 }}
      serviceAccountName: {{ include "common.lib.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.config.sharepointPfx }}
      volumes:
        - name: secret-volume
          secret:
            secretName: {{ include "common.lib.fullname" . }}-service-volume-config
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          image: {{ .Values.image.repo }}:{{ .Values.image.tag }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          envFrom:
            {{- if .Values.existingSecret }}
            {{- with .Values.existingSecret }}
            - secretRef:
                {{- tpl . $ | nindent 16 }}
            {{- end }}
            {{- else }}
            - secretRef:
                name: {{ include "common.lib.fullname" . }}-service-secret
            {{- end }}
            - configMapRef:
                name: {{ include "common.lib.fullname" . }}-configmap
          {{- if .Values.config.sharepointPfx }}
          volumeMounts:
              - name: secret-volume
                mountPath: /sharepoint/config/privatekey.pfx
                subPath: privatekey.pfx
          {{- end }}
          livenessProbe:
            httpGet:
              path: /health
              port: http
          readinessProbe:
            httpGet:
              path: /health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
