{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-service-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.config.secrets.dbPassword | quote }}
  AUTH_CLIENT_SECRET: {{ .Values.config.secrets.oidcClientSecret | quote }}
---
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-service-volume-config
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  privatekey.pfx: {{ .Values.config.privateKeyPfx | quote }}
  site-config.json: {{ .Values.config.siteConfigJson | quote }}