{{- if not .Values.config.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-service-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.config.secrets.dbPassword | quote }}
  AUTH_CLIENT_SECRET: {{ .Values.config.secrets.oidcClientSecret | quote }}
---
{{- end }}
{{- if .Values.config.sharepointPfx }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.fullname" . }}-service-volume-config
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
data:
  privatekey.pfx: {{ .Values.config.sharepointPfx | b64enc }}
---
{{- end }}
{{- if .Values.imageCredentials -}}
  {{- range $v := .Values.imageCredentials }}
  {{- with $ -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-{{ $v.name }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" $v.registry $v.username $v.password $v.email (printf "%s:%s" $v.username $v.password | b64enc) | b64enc }}
---
{{- end }}
{{- end }}
{{- end }}
