{{- if .Values.istioIngress.enabled }}
{{- if .Values.gatewayModes.outboundDlp.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "gateway.name" . }}-outbound-dlp
spec:
  selector:
    {{- toYaml .Values.istioIngress.gatewaySelectors | nindent 12 }}
  servers:
    - port:
        number: {{ .Values.gatewayModes.outboundDlp.port }}
        name: gateway
        protocol: TCP
      hosts:
        {{- toYaml .Values.istioIngress.ingressHostnames | nindent 12 }}
{{- end }}
{{- end }}
