{{- if .Values.istioIngress.enabled }}
{{- if .Values.gatewayModes.outboundDlp.enabled }}
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: gateway
spec:
  gateways:
    - {{ include "gateway.name" . }}-outbound-dlp
  hosts:
    - {{ include "gateway.name" . }}-{{ .Values.gatewayModes.outboundDlp.name }}
  tcp:
    - match:
        - port: {{  .Values.gatewayModes.outboundDlp.port }}
      route:
        - destination:
            host: {{ include "gateway.name" . }}-{{ .Values.gatewayModes.outboundDlp.name }}
            port:
              number: {{ .Values.gatewayModes.outboundDlp.port }}
{{- end }}
{{- end }}
