{{- if and .Values.gatewayModes.inboundEncrypt.enabled (not .Values.additionalConfig.abac.enabled) }}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: gateway
  name: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundEncrypt.name }}
data:
  GATEWAY_MODE: "encrypt-everything"
  GATEWAY_TOPOLOGY: "inbound"
  GATEWAY_REPLACEMENT_FROM_ENABLED: {{ .Values.additionalConfig.replaceFromEnabled | quote }}
{{- end }}



