{{- if eq .Values.gatewayModes.outboundEncrypt.enabled true }}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: gateway
  name: {{ .Chart.Name }}-{{ .Values.gatewayModes.outboundEncrypt.name }}
data:
  GATEWAY_MODE: "encrypt-everything"
  GATEWAY_TOPOLOGY: "outbound"
  GATEWAY_DECRYPT_THEN_ENCRYPT: {{ .Values.additionalConfig.decryptThenEncrypt | quote }}
{{- end }}



