{{- if .Values.gatewayModes.inboundAbacEncrypt.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: gateway
  name: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundAbacEncrypt.name }}
data:
  GATEWAY_MODE: "abac-encrypt"
  GATEWAY_TOPOLOGY: "inbound"
{{- end }}
