{{- if eq .Values.gatewayModes.outboundDlp.enabled true }}
{{- if .Values.additionalConfig.abac.enabled}}
kind: ConfigMap
apiVersion: v1
metadata:
  labels:
    app: gateway
  name: {{ .Chart.Name }}-{{ .Values.gatewayModes.outboundDlp.name }}-tagging
data:
  GRPC_PORT: {{ .Values.taggingService.port | quote }}
{{- if .Values.additionalConfig.abac.configService.taggingArtifactId }}
  CONFIG_ARTIFACT_ID: {{ .Values.additionalConfig.abac.configService.taggingArtifactId | quote }}
  CONFIG_SERVICE_ENDPOINT: {{ .Values.additionalConfig.abac.configService.url | quote }}
  CONFIG_SERVICE_POLLING_MAX: {{ .Values.additionalConfig.abac.configService.pollingMax | quote}}
  CONFIG_SERVICE_POLLING_MIN: {{ .Values.additionalConfig.abac.configService.pollingMin | quote}}
  OIDC_TOKEN_ENDPOINT: {{ .Values.additionalConfig.abac.oidcTokenUrl | quote }}
{{- if .Values.additionalConfig.abac.attrService.url }}
  ATTR_SERVICE_POLLING_MAX: {{ .Values.additionalConfig.abac.attrService.pollingMax | quote}}
  ATTR_SERVICE_POLLING_MIN: {{ .Values.additionalConfig.abac.attrService.pollingMin | quote}}
  ATTR_SERVICE_AUTH_CLIENT_ID: {{ .Values.additionalConfig.abac.oidcClientId | quote}}
  ATTR_SERVICE_ENDPOINT: {{ .Values.additionalConfig.abac.attrService.url | quote}}
{{- end}}
{{- else }}
  CONFIG_PATH: "/tagging-pdp/config.yaml"
{{- end }}
{{- end }}
{{- end }}
