apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-oauth2-token-refresher
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
spec:
  schedule: "*/55 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: oauth2-token-refresher
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              command:
                - "/bin/sh"
                - "-c"
                - |
                  java -cp "/usr/local/smtp-proxy/smtp-proxy/target/lib/smtp-proxy-{{ .Values.appVersion }}.jar:/usr/local/smtp-proxy/smtp-proxy/target/lib/*" com.virtru.gateway.smtpproxy.oauth2.TokenRefresher
              env:
                - name: OAUTH2_REFRESH_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-oauth2-secret
                      key: oauth2-refresh-token
                - name: OAUTH2_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-oauth2-secret
                      key: oauth2-client-id
                - name: OAUTH2_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-oauth2-secret
                      key: oauth2-client-secret
          restartPolicy: OnFailure
