apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-oauth2-secret
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
stringData:
  OAUTH2_REFRESH_TOKEN: {{ .Values.appSecrets.oauth2.refreshToken | b64enc | quote }}
  OAUTH2_CLIENT_ID: {{ .Values.appSecrets.oauth2.clientId | b64enc | quote }}
  OAUTH2_CLIENT_SECRET: {{ .Values.appSecrets.oauth2.clientSecret | b64enc | quote }}
  OAUTH2_ACCESS_TOKEN: {{ .Values.appSecrets.oauth2.accessToken | b64enc | quote }}
