apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secrets
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}
    app.kubernetes.io/component: gateway
type: Opaque
data:
  gateway-amplitude-api-key: {{ .Values.appSecrets.amplitudeToken | b64enc | quote }}
  gateway-api-token-name: {{ .Values.appSecrets.gatewayApiTokenName | b64enc | quote }}
  gateway-api-token-secret: {{ .Values.appSecrets.gatewayApiSecret | b64enc | quote }}
  {{- if eq .Values.standardConfig.headers.xHeaderAuthEnabled true }}
  gateway-xheader-auth-secret: {{ .Values.appSecrets.headers.xHeaderAuthSecret | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.additionalConfig.saslAuth.smtpdUpstream.enabled true }}
  gateway-sasl-auth-upstream: {{ .Values.appSecrets.saslAuth.smtpdUpstream.accounts | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.additionalConfig.saslAuth.smtpDownstream.enabled true }}
  gateway-sasl-auth-downstream: {{ .Values.appSecrets.saslAuth.smtpDownstream.accounts | b64enc | quote }}
  {{- end }}
  {{- if eq .Values.additionalConfig.abac.enabled true }}
  oidc-client-secret: {{ .Values.appSecrets.oidcClientSecret | b64enc | quote }}
  {{- end }}

