{{- if and .Values.gatewayModes.inboundDecrypt.enabled (not .Values.additionalConfig.abac.enabled) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundDecrypt.name }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
    app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundDecrypt.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundDecrypt.name }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.gatewayModes.inboundDecrypt.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundDecrypt.name }}
    app.kubernetes.io/instance: {{ .Chart.Name }}-{{ .Values.gatewayModes.inboundDecrypt.name }}
{{- end }}