{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-configsvc
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRESQL_PASSWORD: {{ .Values.secrets.configuration.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-attributes-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.attributes.dbPassword }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.attributes.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlements-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.entitlements.dbPassword | quote }}
  OIDC_CLIENT_SECRET: {{ .Values.secrets.entitlements.clientSecret | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlement-store-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.entitlementStore.dbPassword }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-entitlement-pdp-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  opaPolicyPullSecret: {{ .Values.secrets.opaPolicyPullSecret | default "opaPolicyPullSecret" }}
---
{{- if index .Values "tagging-pdp" "config" "oidcSecretName" }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.lib.name" . }}-tagging-pdp-secret
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  ATTR_SERVICE_AUTH_CLIENT_SECRET: {{ .Values.secrets.taggingPDP.clientSecret | quote }}
  CONFIG_SERVICE_AUTH_CLIENT_SECRET: {{ .Values.secrets.taggingPDP.clientSecret | quote }}
  OIDC_TOKEN_ENDPOINT: {{ include "shp.oidc.tokenUrl" . | quote }}
---
{{- end }}
{{- end }}

