{{- if .Values.virtruProxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gateway.name" . }}-virtru-proxy
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}-virtru-proxy
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "gateway.name" . }}-virtru-proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "gateway.name" . }}-virtru-proxy
    spec:
      imagePullSecrets:
        - name: {{ .Values.virtruProxy.imagePullSecret }}
      containers:
          - name: virtru-proxy
            image: {{ .Values.virtruProxy.image.repo }}:{{ .Values.virtruProxy.image.tag }}
            imagePullPolicy: IfNotPresent
            env:
              - name: configsvc.endpoint
                value: {{ .Values.virtruProxy.configsvc.endpoint }}
              - name: LOG_LVL_SERVICE
                value: DEBUG
              - name: configsvc.gatewayKey
                value: {{ .Values.virtruProxy.configsvc.gatewayKey }}
            ports:
              - name: http
                containerPort: {{ .Values.virtruProxy.port }}
                protocol: TCP
{{- end }}