apiVersion: v1
kind: Service
metadata:
  name: {{ include "gateway.name" . }}-virtru-proxy
  labels:
    app.kubernetes.io/name: {{ include "gateway.name" . }}-virtru-proxy
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
      appProtocol: http
  selector:
    app.kubernetes.io/name: {{ include "gateway.name" . }}-virtru-proxy