{{- if and ( .Values.ingress.istio.enabled ) ( not .Values.ingress.istio.existingGateway ) }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "common.lib.fullname" . }}-gateway
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
spec:
  selector:
    istio: {{ .Values.ingress.istio.ingressSelector }}
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP2
      hosts:
        - {{ include "sharepoint.ingressHostname" . }}
      tls:
        httpsRedirect: true # sends 301 redirect for http requests
    - port:
        number: 443
        name: https-443
        {{- if .Values.ingress.istio.tls.enabled }}
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: {{ include "sharepoint.ingress.tlsCredName" . }}
        {{- else }}
        protocol: HTTP2
        {{- end }}
      hosts:
        - {{ include "sharepoint.ingressHostname" . }}
---
{{- if .Values.ingress.istio.tls.enabled }}
  {{- if not .Values.ingress.istio.tls.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sharepoint.ingress.tlsCredName" . }}
type: kubernetes.io/tls
data:
  {{ ( include "sharepoint.ingress.gen-certs" . ) }}
  {{- end }}
  {{- end }}
{{- end }}