{{- if or ( .Values.ingress.istio.enabled ) ( .Values.global.istioEnabled ) }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: sharepoint-svc
spec:
  gateways:
    - {{ include "sharepoint.istio.gateway" . }}
  hosts:
    - '*'
  http:
    - match:
        - uri:
            prefix: {{ .Values.ingress.istio.ingressPrefix }}
      rewrite:
        uri: /
      name: sharepoint
      route:
        - destination:
            host: {{ include "common.lib.fullname" . }}
            port:
              number: {{ .Values.service.port }}
{{- end }}