apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "common.lib.name" . }}-docker-registry-certs
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
  {{ ( include "registry.gen-certs" . ) }}