apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: scp-docker-registry-certs
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
  {{ ( include "registry.gen-certs" . ) }}