## @section Postgresql Chart Overrides
postgresql:
  ## @param postgresql.fullnameOverride Postgresql Name override
  fullnameOverride: postgresql
  image:
    ## @param postgresql.image.debug Debug Flag
    debug: true
    ## @param postgresql.image.tag Image Tag
    tag: "11"
  auth:
    ## @param postgresql.auth.existingSecret Existing secret for postgres auth settings
    existingSecret: >
      {{ include "postgresql.primary.fullname" . }}-secret
  primary:
    ## @skip postgresql.primary.annotations.proxy.istio.io/config
    annotations:
      proxy.istio.io/config: '{ "holdApplicationUntilPRoxyStarts": true }'
    initdb:
      ## @param postgresql.primary.initdb.user user for init script execution
      user: postgres
      ## @param postgresql.primary.initdb.scriptsSecret Secret containing init db scripts
      scriptsSecret: >
        {{ include "postgresql.primary.fullname" . }}-initdb-secret

## @section Secret Generation Parameters
secrets:
  postgresql:
    ## @param secrets.postgresql.dbPassword password for postgres user
    dbPassword:
  attributes:
    ## @param secrets.attributes.dbPassword postgres password for attributes svc user
    dbPassword:
  configuration:
    ## @param secrets.configuration.dbPassword postgres password for config svc user
    dbPassword:
  entitlementStore:
    ## @param secrets.entitlementStore.dbPassword postgres password for entitlement-store svc user
    dbPassword:
  entitlements:
    ## @param secrets.entitlements.dbPassword postgres password for entitlements svc user
    dbPassword:
  keycloak:
    ## @param secrets.keycloak.dbPassword postgres password for keycloak svc user
    dbPassword:
  sharepoint:
    ## @param secrets.keycloak.dbPassword postgres password for sharepoint svc user
    dbPassword: