global:
  imagePullSecrets:

config:
  logLevel: INFO
  #The tagging config yaml- use --set-file on deploy; optional - otherwise use config svc as the source
  configFile:
  # The configuration service endpoint and artifact for the tagging svc
  configSvc:
    url: http://configuration:8080/configuration
    artifactId: taggingpdp.test
    # Max polling time in seconds
    pollingMax: 300
    # Min polling time in seconds
    pollingMin: 30
  attrSvc:
    # Optional attribute service url
    url:
    # Max polling time in seconds
    pollingMax: 300
    # Min polling time in seconds
    pollingMin: 30
  # Optional OIDC Client id
  oidcClientId:
  # Optional OIDC Client Secret
  oidcClientSecret:
  # Existing client secret w/ AUTH_CLIENT_SECRET key
  oidcSecretName:

service:
  type: ClusterIP
  port: 8080

replicaCount: 1

autoscaling:
  enabled: false

# -- Select a specific name for the resource, instead of the default, taggingpdp
nameOverride: ""

# -- The fully qualified appname override
fullnameOverride: ""

# -- Values for the deployment `spec.template.metadata.annotations` field
podAnnotations: {}

# -- Values for deployment's `spec.template.spec.securityContext`
podSecurityContext: {}

# -- Values for deployment's `spec.template.spec.containers.securityContext`
securityContext: {}

# A service account to create
serviceAccount:
  # -- Specifies whether a service account should be created
  create: false
  # -- Annotations to add to the service account
  annotations: {}
  # -- The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: null

image:
  tag: sha-f3f0116
  repo: ghcr.io/virtru-corp/tagging-pdp/tagging-pdp-grpc
  # image pull secret, also used by the grpc-gateway image if enabled.
  pullSecrets:
    - replace_me
  pullPolicy: IfNotPresent

# GRPC Gateway settings
gateway:
  enabled: true
  replicaCount: 1
  port: 8080
  podAnnotations: {}
  # additional prefix for path(e.g. ingress) for swagger ui
  pathPrefix: ""
  image:
    tag: 0.1.0
    repo: ghcr.io/virtru-corp/tagging-pdp/tagging-pdp-grpc-gateway
    pullPolicy: IfNotPresent