name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  push:
    branches: ["main"]

jobs:
  checks:
    uses: virtru-corp/.github/.github/workflows/github-pages-publish.yaml@SRE-4834/add-github-pages-publish-workflow
