{{/*
  Create a white space delimited list of expected certs to be loaded into the truststore
  */}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-cabundles
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
data:
{{- if .Values.trustedCertSecret }}
{{- $s := (lookup "v1" "Secret" .Release.Namespace .Values.trustedCertSecret) }}
{{- $cert_list:= list }}
{{- range $k,$v := index $s "data" }}
{{- $cert_list = append $cert_list ( printf "/etc/x509/https/%s" $k ) }}
{{- end }}
{{- $bundlestr := join " " $cert_list }}
  X509_CA_BUNDLE: {{ $bundlestr | quote}}
{{- else }}
  X509_CA_BUNDLE: ""
{{- end}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-custom-entrypoint
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
binaryData:
  {{ range $path, $bytes := .Files.Glob (printf "kc_custom_entrypoint.sh")}}
  {{ $name := base $path }}
  {{- printf "%s" $name}}{{ print ": "}}{{ $.Files.Get $path | b64enc }}
  {{ end }}
