{{/*
  Secret for keycloak admin user and db connection values
  */}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.keycloak.fullnameOverride }}-extraenv
  labels:
    {{- include "common.lib.labels" . | nindent 4 }}
type: Opaque
stringData:
  KEYCLOAK_ADMIN: {{ .Values.secrets.keycloak.adminUsername }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.secrets.keycloak.adminPassword}}
  KC_DB_USERNAME: "keycloak_manager"
  KC_DB_PASSWORD: {{ .Values.secrets.keycloak.dbPassword }}
  KC_DB_URL_HOST: {{ .Values.global.opentdf.common.postgres.host }}
  KC_DB_URL_DATABASE: {{ .Values.keycloak.externalDatabase.database }}
  JKS_TRUSTSTORE_PASSWORD: {{ randAlphaNum 32 | quote }}
